### ISSUE TITLE
WhatsApp++ 2.17.7 T 1.7r-71 Duplicate App.ipa

### ISSUE THREAD

**Issue by TariqFakhouri** [JMccormick264/PPAppsIPARepo#10]
It Keeps Telling Me This:
![cydia impactor](https://cloud.githubusercontent.com/assets/10964274/23748421/08a78488-04dd-11e7-8893-fd10f6c9dae4.png)

**Comment by JMccormick264** [comment]
I will take a look at that when I get home. Thank you for letting me know.

**Comment by JMccormick264** [comment]
Fixed. I just forgot to name the non duplicate app correctly.
