### ISSUE TITLE
New Duplicated App of Whatsapp

### ISSUE THREAD

**Issue by rohitahuja333** [JMccormick264/PPAppsIPARepo#12]
Can we not make something which will replace whatsapp ++ duplicate app with latest whatsapp++

Like we were on 2.17.7 version [duplicate whatsapp++]
Can't we make something, that after installing 2.17.10 version [duplicate whatsapp++] it replaces the previous one, and chats remain there..

currently 2.17.7 duplicate whatsapp++ is appearing separately from 2.17.10 duplicate whatsapp++

**Comment by JMccormick264** [comment]
Please make a report on the WhatsApp issue repo in Unlimapps GitHub.

**Comment by JMccormick264** [comment]
This is not possible on sideload. Just got word from Unlim. I'm sorry
