### ISSUE TITLE
Feature: Playback speed >2 and maintain pitch 

### ISSUE THREAD

**Issue by 0LoveToLearn0** [JMccormick264/PPAppsIPARepo#124]
Could you increase the max speed to 3.00 (or make it customizable, on the computer it is possible to go beyond 2.00 without issues)?
The "video speed controller“ on chrome doesn’t seem to change the pitch of a video when speeding it up; would it be possible to add this option to YouTube++?

**Comment by JMccormick264** [comment]
This isn't the place for feature requests. That would be here https://github.com/eni9889/YT-PP-Issues
