### ISSUE TITLE
Snacpat ban/lock on all versions of Snap++

### ISSUE THREAD

**Issue by mattba545** [JMccormick264/PPAppsIPARepo#126]
I got banned/locked recently few times, I had 10.19.1 and 10.19.5, and I think it's the same on the 10.27.1.1.
Is there going to be a fix for this? I'm currently on 48h ban, I think, I hope it isn't 1 week.

**Comment by JMccormick264** [comment]
I am not the developer of the tweak. I just package the tweak with the app.
