### ISSUE TITLE
Any way to download older version?

### ISSUE THREAD

**Issue by veraverto** [JMccormick264/PPAppsIPARepo#138]
Hello!

Is there any way to download older versions of for example Spotify++? I don't like the redesign (on which you can't switch to repeat a song directly) and it is significantly slower on my phone.

Best regards!

**Comment by wiredbrother** [comment]
Go into the Spotify repo folder, then when you could download the IPA click the "History" button on the right top corner. Select the version you are looking for, then once you click the version you want it will redirect you to the master repo however much time back. You then will redirect yourself back to Spotify++ and it should be in the version you selected. Enjoy!

**Comment by veraverto** [comment]
Ah thanks a lot! I was already in the history tab but didn't manage to find the old version. I thought they were deleted once a new version is uploaded.
