### ISSUE TITLE
Spotify++ crash when Sideloading

### ISSUE THREAD

**Issue by Nigween** [JMccormick264/PPAppsIPARepo#139]
Downloaded app and tried to sideload into Iphone 8 Plus via Impactor. All goes well until impactor tried to install files related to "watch" (assuming smartwatch compatibility). Freezes for a couple seconds then crashes. Problem does not occur when installing older IPA versions (ie, the version linked on julioverne's twitter). 

Oberservation after crash: checked task manager, impactor is now running in background but is frozen (not processing anything). Please see attached image.
![Impactor Crash](https://user-images.githubusercontent.com/49767064/56391363-4be0b980-61e3-11e9-8d98-3952bc54ba41.PNG)

**Comment by god1121** [comment]
Having the same problem, crashes while loading "watch" related. 
Used v8.4.3 for now, sideloaded fine.

**Comment by jgkrapster** [comment]
why does it say WATCH/Whatsapp before it crashes? hmmmmmm looks like spyware.....

**Comment by jebthedev** [comment]
I also have this problem, (iPhone 8, via impactor on mac).
Impactor crashes ("Impactor has unexpectedly quit").
I have installed other apps successfully, so it isn't an issue with impactor.

**Comment by fleazz** [comment]
this older one worked for me [](https://ipswbeta.com/spotify-plus-plus-ipa/)

**Comment by adamnorris10** [comment]
Here, this is a direct download of v8.5.0_v1.0 without ads: https://www.dropbox.com/s/32dd1nav96uqlv8/Spotify%2B%2B%20v8.5.0_v1.0.ipa?dl=0

**Comment by Nigween** [comment]
JM fixed this issue in the most recent update to Spotify. The issue will not be closed.
