### ISSUE TITLE
YouTube ++ 10 Second Skips Don't Work On iPad

### ISSUE THREAD

**Issue by GamerKid303** [JMccormick264/PPAppsIPARepo#14]
When I try to use the seconds skips, it always takes me to the first ten seconds of the video, no matter when I use it.

**Comment by JMccormick264** [comment]
Please make a issue report in the YT++ section. Use [this link](https://github.com/JMccormick264/PPAppsIPARepo/blob/master/Issue%20Request%20Links.md) and find GR YouTube++ link
