### ISSUE TITLE
Pandora++ v8.4_v007.ipa

### ISSUE THREAD

**Issue by avogarden** [JMccormick264/PPAppsIPARepo#16]
Getting error: installation.cpp:42 Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.S8hBlo/extracted/Payload/Pandora.app/PlugIns/WatchKit Extension.appex : 0xe8008017 (A signed resource has been added, modified, or deleted) This error happens on iOS Mac Sierra
I tried to install via Windows 10 x64 Creators Update, using Impactor 9.39 and it just stalls on Verifying App

**Comment by JMccormick264** [comment]
Update to the latest Impactor update. I just tried it with the latest and it worked for me. If you need a link to .39 in case you need it again, let me know.

**Comment by avogarden** [comment]
Wow, fast response...Thanks-Unfortunately, the latest version of Pandora
just hangs at the Verifying Application stage using latest version of Cydia
Impactor 9.4.1.  I verified that my Mac version of impactor is the latest,
which it is.  I do have a backup copy of impactor 9.39.  I had been using
this version since I was getting errors on the install for Spotify++ ipa.
However, I just installed Spotify++ v8.4.0_v005 using 9.41.  Maybe it's
just my machines, your work is so very appreciated.  I do have the previous
version of Pandora ipa, which is working...FYI...I do check your site at
least once a day. You are AWESOME!

**Comment by JMccormick264** [comment]
Thank you :) I am not sure why Pandora isn't working for you..that is a weird issue. Is it the same error even on 9.4.1?

**Comment by avogarden** [comment]
Yes, it still does not install on my iPhone 6+ running 10.3.1, using
Impactor 9.4.1, Windows version 1703, OS build 15063.250, just hangs at the
Verifying Application stage...not a big deal, since I have the previous
version....I just deleted and reinstalled Spotify++, YouTube++  no ads
(your latest versions), and Pandora v.8.3.2_007.  Maybe I will have better
luck with the next Pandora version....no worries.

**Comment by JMccormick264** [comment]
possibly. Just keep an eye out for when Pandora comes out with an Update. Not sure why this happens though

**Comment by JMccormick264** [comment]
Try the newest IPA I just pushed. let me know if it works

**Comment by avogarden** [comment]
You are the best! I just installed the latest version....success!
