### ISSUE TITLE
Spotify Duplicate

### ISSUE THREAD

**Issue by onurtirpan** [JMccormick264/PPAppsIPARepo#18]
There is no Spotify Duplicate IPA, any chance to make one?

Thanks!

**Comment by JMccormick264** [comment]
Why would you need a duplicate app for Spotify?

**Comment by onurtirpan** [comment]
Since I dont have developer account, my IPAs expires every 7 days and I usually run out of music since I can only have one Spotify at the time.

**Comment by JMccormick264** [comment]
check my readme on the repo. It is a enterprise signed App without the need for a computer to install. Just click on the link on your phone, and it will install. You will have the apps signed for a year.

**Comment by ascarrambad** [comment]
actually could be useful. Spotify++ seems not to support CarPlay, whereas the standard app store version does.

**Comment by JMccormick264** [comment]
Added the Duplicate to my repo. Let me know if it works.

**Comment by ascarrambad** [comment]
working, thanks mate! keep up the good work

**Comment by JMccormick264** [comment]
You're welcome :)

**Comment by Boki99** [comment]
Hello. Im searching for Spotify app that works with Carplay. I sideloaded spotify++ with Impactor but at Carplay stil not works to me. Am I missing something please help?
