### ISSUE TITLE
Snapchat++ No Notifications

### ISSUE THREAD

**Issue by pdxvr** [JMccormick264/PPAppsIPARepo#20]
I think it's well known that notifications don't work but there is no new issue on it.

**Comment by pdxvr** [comment]
Apparently push notifications will never work on a side-loaded app if anyone is wondering what the deal is

**Comment by JMccormick264** [comment]
Yes it will. check the readme on my repo. Just go to those links from your phone and the IPA will install. I do NOT control that site. So I do not know when IPAs get updated. The IPAs on that site do have push notifications. [Check my post here](https://www.reddit.com/r/iPAHub/comments/6c8tky/update_push_notifications_links_actually_works/)

**Comment by pdxvr** [comment]
I got the info from you. You said somewhere sideloaded apps will never have push. The ones you link to in that post aren't sideloaded.

**Comment by JMccormick264** [comment]
yes they are. You don't need a JB to install them. I am not sure how the guy did it. But the ones in the post I linked do work. Just click on a IPA from that site from your phone and it will install. Test it yourself with Snapchat or something. Push Notifications do work. But only from that source as of now. I am not sure how he got them to work.

**Comment by pdxvr** [comment]
They are not sideloaded, sideloaded apps are installed by the user from their computer using impactor or xcode, etc. These are downloaded from the internet and they are signed by this service so we don't need to sideload them

**Comment by JMccormick264** [comment]
That is correct. I misunderstood you. Apps installed via xcode or impactor will not have push. You are right on that.
