### ISSUE TITLE
Is it possible to update a ++ app using xcode without having to delete them first?

### ISSUE THREAD

**Issue by gcseed** [JMccormick264/PPAppsIPARepo#26]
Hi guys, I just wonder if it is possible to update a ++ app using xcode without having to delete them first? I tried to build the new version of instagram++ on my phone with the old version still installed, and it wont let me because I already have instagram++, youtube++ and snapchat++ installed. I know that you can only sign 3 apps at once, so does that mean there is no way to replace the current app unless I delete and reinstall them? Please let me know if there is a solution to it, much appreciated!

**Comment by JMccormick264** [comment]
You do have to delete and reinstall them. Otherwise you will get a error when trying to do it if you already have it installed.
