### ISSUE TITLE
new ipa to ipasigner.io

### ISSUE THREAD

**Issue by dlovy** [JMccormick264/PPAppsIPARepo#32]
need this apps
https://f0x.pw/paid/ipa/vks_1.ipa
https://f0x.pw/paid/ipa/vkp_1.ipa

**Comment by IanAndersonAdorjanCS** [comment]
What are these?

**Comment by dlovy** [comment]
Clients of vk.com

**Comment by IanAndersonAdorjanCS** [comment]
Isn't VK under some heat? Something about Blue Whale, Blackmailing, and suicides?

**Comment by dlovy** [comment]
No :)
