### ISSUE TITLE
Instagram ADs remove issue

### ISSUE THREAD

**Issue by nfix** [JMccormick264/PPAppsIPARepo#36]
Hello, I installed latest iOS instagram version 190. When I log into my ++ account to remove ADs everythink is fine, ADs are gone but when I start instagram again ADs are back and I must log into ++ account again and again because ADs are back every few minutes. Please can you fix this bug? Thank you.

**Comment by JMccormick264** [comment]
Please make a issue report here [Link here](https://github.com/eni9889/IG-PP-Issues)

**Comment by JMccormick264** [comment]
@nfix I have made Unlim aware of the issue. He will be looking into it.

**Comment by JMccormick264** [comment]
Issue has been fixed.
