### ISSUE TITLE
WhatsApp + Watusi (newer Version; 0.12.1)

### ISSUE THREAD

**Issue by KuroTheBang** [JMccormick264/PPAppsIPARepo#37]
Hey, since your WhatsApp w/ Watusi is 0.9.15, so very outdated. could you maybe update Watusi?

http://ideviceteam.com/ipa_signed/WhatsApp_v2.17.22_Watusi2_v0.12.1.ipa

Here is an iPA with Watusi 0.12.1, which also supports Status modifications

**Comment by JMccormick264** [comment]
Will do that in the morning

**Comment by JMccormick264** [comment]
Updated the IPA
