### ISSUE TITLE
Spotify v8.4.3 cracked Premium issues

### ISSUE THREAD

**Issue by Nmzik** [JMccormick264/PPAppsIPARepo#38]
The cracked version of Spotify doesn't work. Premium features (except offline listening) don't work. Please fix it!

**Comment by kakaswr22** [comment]
tweaked Spotify offline not included mate since from beginning (kakaswr22)

**Comment by JMccormick264** [comment]
Spotify patched that by moving the Authentication to server sided. It will most likely never work. Even JB tweaks I used in the past do not work anymore. Same issue with SoundCloud++
