### ISSUE TITLE
What happened to Pandora++?

### ISSUE THREAD

**Issue by Emoinm** [JMccormick264/PPAppsIPARepo#39]
I deleted it to see if i could fix an issue (issue being the timer left would show 7:00, when the song would be like 4:00) I can't redownload it as it's not on the website and the link here doesn't work 😢

**Comment by JMccormick264** [comment]
1. I do not own or control the site.
2, What isn't working on this repo?

**Comment by Emoinm** [comment]
Oh didn't know you weren't apart of the website. Also the Pandora++ says" Unable to Download App" on mobile 😢

**Comment by JMccormick264** [comment]
I have no clue. All I can say is to try again or try using cellular. I do not control the site or the IPAs that go on the site.

**Comment by Emoinm** [comment]
The download here also doesn't work is what I'm saying

**Comment by AnyoeDove** [comment]
@ipasigner
