### ISSUE TITLE
Trying to Install Snapchat++ - Stuck on Waiting

### ISSUE THREAD

**Issue by Sponitz** [JMccormick264/PPAppsIPARepo#40]
I tried to install Snapchat++,  but the app is stuck on waiting. I tried to pause and un-pause, restart the phone, and cancel and reinstall multiple times. Any ideas?

**Comment by Sponitz** [comment]
I did try other apps, and they install fine. It only seems to be happening with Snapchat.

**Comment by JMccormick264** [comment]
I do not own or run the site. Try installing on cellular and not on wifi.

**Comment by Sponitz** [comment]
That's the only way I tried.

**Comment by xthemikx911** [comment]
The app wont load over cellular, we can only make it on wifi.
