### ISSUE TITLE
Snapchat++ dosnt work

### ISSUE THREAD

**Issue by xthemikx911** [JMccormick264/PPAppsIPARepo#41]
Hi,
  Im using the Snapchat++ and this afternoon it stoped to work. No internet data but the internet is working well. I tryed to uninstall and reinstall but samething. The Snapchat app is working well but not the ++ version for now😕 

Any fix?

Thank
Best regards
Mike

**Comment by JMccormick264** [comment]
What is not working?

**Comment by xthemikx911** [comment]
When im trying to connect, it mention i dont have access to internet

**Comment by xthemikx911** [comment]
'Please check your internet and try again' when i click on connect

**Comment by JMccormick264** [comment]
Ah. Yeah. Snapchat probably just enabled DRM again. You most likely won't be able to sign in.

**Comment by xthemikx911** [comment]
For always?

**Comment by hazemustafa** [comment]
Same issue for me..

**Comment by hazemustafa** [comment]
please fix it

**Comment by kakaswr22** [comment]
Download SCOthman still works :) (kakaswr22)

**Comment by xthemikx911** [comment]
Where can i get it?

**Comment by JMccormick264** [comment]
You can't. Snapchat enabled DRM. Unlim has said multiple times. Check his twitter. He has a job and he does the tweaks as a hobby. Fighting their DRM is basically a full time job.

**Comment by JMccormick264** [comment]
@hazemustafa it won't be fixed. Check Unlims twitter. Don't spam him with emails or tweets asking for it to be fixed. It won't. He doesn't have the time to fight DRM because he has a job already and trying to fight the DRM will take too much time.
