### ISSUE TITLE
Instagram new update issue 

### ISSUE THREAD

**Issue by rikianastasoski** [JMccormick264/PPAppsIPARepo#42]
I know that you dont update the tweaks but do u have connection with the dev of instagram++? cuz i dont like the new update changes: "

> Fixed ++ asks for a confirmation when you double tap a photo, but not when you click the heart button on the bottom left of the picture. If you have "Confirm Like" enabled.

" i actually liked having both of this options, **fast liking with the heart button and double tapping for careful liking** :/ could you contact the dev or tell me how can i reach him so i can tell him to add both options?

**Comment by JMccormick264** [comment]
I do have a good method of contacting Unlim What do you mean by the new changes that you want to make?

**Comment by rikianastasoski** [comment]
@JMccormick264 His "Confirm Like" option only worked when you double tap photos, and now he fixed it to ask for confirmation when u click the heart button, i think a lot of people like me got used to getting confirmation when double tapping and when u want to fast like everything on the feed u just click the heart button, now i get confirmations on both :( i only wanted that option so that people who grab my phone dont like someones old photos and they would get confirmation cuz usually they double tap not click the heart button.

**Comment by JMccormick264** [comment]
Has been fixed in the latest version.
