### ISSUE TITLE
Snapchat ++ connection issues resurfaced. (DRM Re-activated?)

### ISSUE THREAD

**Issue by IanAndersonAdorjanCS** [JMccormick264/PPAppsIPARepo#43]
Hey there JM! I recently notice Snapchat ++ connection issues with the error,"Please check your internet and try again" just wondering if any word of hot-fixes or is DRM (Digital Restrictions Management) in motion? Or reactivated? 
Thanks, Ian Adorjan

**Comment by kakaswr22** [comment]
download snapchat othman which is Called SCOthman it work now perfectly (kakaswr22)

**Comment by IanAndersonAdorjanCS** [comment]
Thanks Kakaswr22 I'll try it maybe.

**Comment by JMccormick264** [comment]
Yes DRM has been re-activated and Unlim does not have the time to fix and fight the DRM because he has a full time job and trying to fight the DRM would take too much time.
