### ISSUE TITLE
Can ipasigner.io write release dates on list ?

### ISSUE THREAD

**Issue by bsormagec** [JMccormick264/PPAppsIPARepo#45]
Can ipasigner.io write release dates on app list ? It will be helpful.

**Comment by IanAndersonAdorjanCS** [comment]
Bsormagec JM has nothing to do with ipasigner.io he doesn't have anything to do with the IPAs or the site. He only is helping getting the word out hope this helps. :)

**Comment by JMccormick264** [comment]
Yes ^^ I do not control the site or the IPAs. So I have no way of knowing what version they are on. He opened a pull request. You can check the Pull Requests on this repo and the 2nd one from the bottom his PR which had the links. I just put those links into the readme.

**Comment by bsormagec** [comment]
Thanks so much we will mention him here :) @ipasigner
