### ISSUE TITLE
Instagram ++ Takes Up Way Too Much Storage

### ISSUE THREAD

**Issue by becazieg** [JMccormick264/PPAppsIPARepo#46]
I am on sideloaded Instagram++ and when I install it, it has the regular Instagram size (under 1GB) and everything is normal. However, after using it for a while (especially after watching videos on the explore page) it starts blowing up and taking up to 2GB of my storage space. I don't understand why it's doing this because the regular Instagram app never did this.
I also do not have any media saved in "media vault" because everything I save directly goes into my camera roll, so it's not because I've downloaded or stored files on the app.

**Comment by JMccormick264** [comment]
Have you tried uninstalling the IPA and re-doing it and see if the storage space has gone down?

**Comment by becazieg** [comment]
yes, doing that makes the storage space go down but it is kind of problematic to have to reinstall the IPA everytime i'm done looking through the explore page. I just don't understand why the storage space would go this high just for using the app.

**Comment by JMccormick264** [comment]
hmm..that is interesting. I will take a look into it and see it happens on my end.

**Comment by JMccormick264** [comment]
I believe this issue has been fixed.
