### ISSUE TITLE
Crash upon opening Spotify++

### ISSUE THREAD

**Issue by benawesome100** [JMccormick264/PPAppsIPARepo#47]
It just crashes when I try open it

I have it Sideloaded on a non-jailbroken iPhone

**Comment by IanAndersonAdorjanCS** [comment]
Hey there Ben Snapchat ++ won't work period now DRM (Digital Restrictions Management) is activated it completely makes the tweak paper weight try the Phantom IPA that has been added.

**Comment by JMccormick264** [comment]
@benawesome100 You need to reimpact the IPA (open cydia impactor, drag and drop the IPA) and go through that process.

**Comment by IanAndersonAdorjanCS** [comment]
Well it did say Snapchat ++ but he changed it lmao. :3
