### ISSUE TITLE
Snapchat++, Can Not Connect

### ISSUE THREAD

**Issue by itsGord** [JMccormick264/PPAppsIPARepo#48]
Downloaded Snapchat++, and used Cydia Impactor and when I went to log in it said could not connect. I tried multiple times and still go the same message and even tried wireless connection and a VPN, still nothing worked.

**Comment by xthemikx911** [comment]
The DRM is enable. We can't use Snapchat++ anymore until it was enable :(

**Comment by JMccormick264** [comment]
@xthemikx911 @itsGord It is working for me and Unlim on Jailbreak. We do not know why it won't work on sideload.

**Comment by itsGord** [comment]
@JMccormick264 do you know if there is a jailbreak for ios 10.3 out right now?

**Comment by HugaShire** [comment]
@itsGord Please ask google. And no.
