### ISSUE TITLE
JM why is every IPA crack going to shite?

### ISSUE THREAD

**Issue by IanAndersonAdorjanCS** [JMccormick264/PPAppsIPARepo#49]
Hey JM what are we to expect any word if there's any hope on fixes for all these patches. Also I'm a little confused. Spotify ++ wasn't working I seen the closed issue but now it works after the re-upload why is stuff going so goofy for?

**Comment by JMccormick264** [comment]
If you were referring to the Offline feature not working, that will not work no matter what. the authentication and check for having the offline feature is done server sided. As of now you will have everything but Offline listening.

**Comment by IanAndersonAdorjanCS** [comment]
I knew about that but other than that stuff in my experience is just getting a little rickety. Something just feels off that's all. Thanks.
