### ISSUE TITLE
Spotify 8.4.3

### ISSUE THREAD

**Issue by Nmzik** [JMccormick264/PPAppsIPARepo#50]
Am i doing something wrong? I downloaded spotify ++ ipa from https://ipasigner.io/ via my iPhone. I assume it gives all premium features (well, at least it should give you unlimited skips + song scrolling + no ads + extreme sound quality, but not offline listening). The problem i have is that when i open downloaded app i don't have any of these features. but i DO see Spotlife menu in settings + account has "Premium" subscription. Strangely enough, when i download ipa from this repo and sign it by myself(7 days) all Premium features work! WHAT am i doing wrong? Thanks

**Comment by JMccormick264** [comment]
I do not know. I do not control the IPAs on ipasigner.io. So I cannot answer that. I am sorry :(

**Comment by IanAndersonAdorjanCS** [comment]
JM I believe not assume that https://ipasigner.io/ uses your IPA's from this repo. call me skeptical but your previous version of spotify ++ that you had here before you re-uploaded it. It had the same problems. So seems fishy but who knows.

**Comment by JMccormick264** [comment]
That is a possibility. Idk though.

**Comment by IanAndersonAdorjanCS** [comment]
Well just to beat around the bush I'd put some kind of watermark in the app code nothing harmful or anything but a code or keyword to know if it's yours or not. Or who ever you're partnered with who does them.

**Comment by JMccormick264** [comment]
I am not partnered with anyone. All the IPAs I made myself using unlimapps's ppsideloader and other tweak files. I upload them by myself.

**Comment by IanAndersonAdorjanCS** [comment]
Okay I'm sorry I didn't know but I appreciate your work I would just hate to see someone free load off of it.

**Comment by JMccormick264** [comment]
Yeah. I know people appreciate it. And I enjoy it. So I will keep doing it regardless. Thank you though! Don't plan on stopping any time soon. I enjoy this
