### ISSUE TITLE
Youtube Music unrestricted country not working

### ISSUE THREAD

**Issue by ascarrambad** [JMccormick264/PPAppsIPARepo#51]
Hi, i tried to download many versions of Youtube Music during time but none of those nor the actual one seems to keep word on the unrestricted country usage, therefore i can't use it as i'm living in a country not supported. Any chance of fixing it?

**Comment by dlovy** [comment]
Use vpn

**Comment by ascarrambad** [comment]
can't do that, because it asks for a google account, which undermines the fake country that the vpn provides

**Comment by JMccormick264** [comment]
I do not make the tweak nor do I have any influence over the fixes.
