### ISSUE TITLE
Is there a way to install the ipa's from this site on my phone, cause ipasigner.io versions are behind

### ISSUE THREAD

**Issue by nickterhaar** [JMccormick264/PPAppsIPARepo#54]
As the title already tells you, is there a way to install those ipa's from this github site on my iphone like ipasigner.io?

The ipa's on ipasigner.io are a bit behind compared to the ipa's on this github page. Or did I do something wrong?

**Comment by JMccormick264** [comment]
My GitHub has nothing to do with the signing site. All I did was add the links he made when he made the pull request. My links are made for cydia impactor or signing services that allow you to custom upload ipas for signing.
