### ISSUE TITLE
latest Phantom

### ISSUE THREAD

**Issue by archipilot** [JMccormick264/PPAppsIPARepo#56]
can you upload the latest Phantom ipa. Cheers

**Comment by JMccormick264** [comment]
Are you getting a connection error?

**Comment by archipilot** [comment]
yes. the guy who creates Phantom has updated and solved the issue. but I don't have cydia so I always rely on your side loaded ipa.

**Comment by JMccormick264** [comment]
Yes. He has updated it for JB. And I can verify that it works. But he has not updated it for sideload. The version still says v1.1 for the sideloaded files.

**Comment by JMccormick264** [comment]
I will update Phantom when he updates It for sideload.
