### ISSUE TITLE
Facebook++ version 93.0 crash

### ISSUE THREAD

**Issue by unityhd** [JMccormick264/PPAppsIPARepo#59]
Hello, i have a problem with all version higher than 86.0 that it crashs at a random time in the news feed. 
It crashs when it goes to the end of the loaded site and it trys to load more posts.
Only the 86.0 version works like a charm, is there any solution for this problem?

**Comment by JMccormick264** [comment]
There is not a solution at this time. It is a weird bug. Crashes for others and other people it works fine.
