### ISSUE TITLE
**EVERYONE WHO USES http://ipasigner.io CLICK HERE**

### ISSUE THREAD

**Issue by IanAndersonAdorjanCS** [JMccormick264/PPAppsIPARepo#60]
Everyone watch out. Ipa signer is acting fishy on IOS 11 beta 1 when you install a app from the sight you’ll get a second one stuck under installing I believe this to be a bug or MALICIOUS posting proof along side.
PROOFING: https://ibb.co/jECznk

**Comment by IanAndersonAdorjanCS** [comment]
JM This could be a serious issue? Why close it for all we know we could be having malicious software right under our noses being installed. Please take this seriously. We don’t know him he just came out of nowhere in the community it’s odd and I don’t care for it.

**Comment by JMccormick264** [comment]
It's not malicious considering Appdb and other signing services do the same thing. It's just how it works. I just tried it with an app store app and it did the same thing. I see nothing wrong. It could just be a issue with iOS 11. the same thing happened with an app store app. No need to jump to conclusions.

**Comment by IanAndersonAdorjanCS** [comment]
Okay I’m sorry.

**Comment by JMccormick264** [comment]
it's alright. No need to be sorry. No harm done
