### ISSUE TITLE
Watusi latest update 

### ISSUE THREAD

**Issue by kakaswr22** [JMccormick264/PPAppsIPARepo#61]
Update watusi to v1.0.0 If you don’t have it I have the ipa file contact me on Twitter kakaswr22

**Comment by NagasakiGG** [comment]
Just upload it somewhere and post here the link :) It's easy for everybody

**Comment by JMccormick264** [comment]
@kakaswr22 Thank you. Uploading it now

**Comment by JMccormick264** [comment]
@NagasakiGG I know where he uploads it to

**Comment by kakaswr22** [comment]
i already upload it ..but i want to you upload it to ipasigner.io plz
