### ISSUE TITLE
Napster++ / Deezer++

### ISSUE THREAD

**Issue by NagasakiGG** [JMccormick264/PPAppsIPARepo#62]
Hey, could you maybe add Napster++ and Deezer++ ?

Here are the latest ++ apps:

https://iparhino.com/dl/n3335sijnpwok4g80g.ipa (Deezer 6.20.1)

https://iparhino.com/dl/u97gdg2ndu8coog0ks.ipa (Napster 5.8)

**Comment by JMccormick264** [comment]
Yes I can.

**Comment by JMccormick264** [comment]
I have updated Napster++ and Deezer++
