### ISSUE TITLE
Update iPAsigner.io YT++?

### ISSUE THREAD

**Issue by HugaShire** [JMccormick264/PPAppsIPARepo#63]
I know you don't have any control, but is there anyway to contact them? I really would love them to update it so I can use the seek 10 Seconds feature

**Comment by JMccormick264** [comment]
@ipasigner ^^

**Comment by HugaShire** [comment]
Well, thanks. But now the certificate was revoked

**Comment by JMccormick264** [comment]
Yeah. I do not know when and if it will come back. I am not the owner.
