### ISSUE TITLE
Won't download

### ISSUE THREAD

**Issue by ryaleemitchell** [JMccormick264/PPAppsIPARepo#64]
My Instagram++ just stopped working out of no where and it said I needed to verify, so I tried to but it didn't work so I deleted Instagram++ and tried to reinstall but it kept saying "cannot download at this time" and I thought it was only my phone but it happened to my friend too! Fix this? Because I LOVE your ++ apps and I'd be really bummed if I can't use it.

**Comment by JMccormick264** [comment]
Where are you downloading the app from?

**Comment by ryaleemitchell** [comment]
I'm downloading the app from this website, the links you put up there for how we can get the ++ apps with push notifications without computer.

**Comment by JMccormick264** [comment]
From what I know ( I am not the owner) the enterprise cert got revoked by Apple. So no IPAs will work

**Comment by boyceree000** [comment]
is this what is causing Spotify to stop working also?

**Comment by JMccormick264** [comment]
Spotify++ from the website? Yes. Any App from that site downloaded will not work.

**Comment by ryaleemitchell** [comment]
Do you know if the owner will create new ones or they like stopped working for good?

**Comment by Yivensky** [comment]
@JMccormick264 Can you add Phantom Lite too ? Currently there are lot of ban and phantom it's the only one who really bypass the DRM and even with that there is some ban...
And between the snap++ from cydia and the same version sideloaded, are they the same risk or sideload is more "detected"?
Thanks

**Comment by ryaleemitchell** [comment]
Do you know if the owner will create new ones or they like stopped working for good?

**Comment by JMccormick264** [comment]
I am not sure. I have no way of contacting the owner.
