### ISSUE TITLE
SoundCloud Premium Tracks

### ISSUE THREAD

**Issue by mikededo4** [JMccormick264/PPAppsIPARepo#67]
Premium tracks have a loading error so I can't listen to them

**Comment by JMccormick264** [comment]
Yes. That is intentional. You can't play them. For the same reason you can't download tracks.

**Comment by mikededo4** [comment]
Not to sound like an ass...but isnt that the purpose of the app? And if so will it ever be returned to normal ?

**Comment by JMccormick264** [comment]
It will not return. And you have No Ads. That is all that you will be given from now on.
