### ISSUE TITLE
Youtube++ +/- seconds do not work

### ISSUE THREAD

**Issue by HugaShire** [JMccormick264/PPAppsIPARepo#7]

**Comment by JMccormick264** [comment]
In what way aren't they working?

**Comment by HugaShire** [comment]
@Jmccormick264 I posted it in the comments

**Comment by JMccormick264** [comment]
Unlim is busy right now with other things. I will let you know when he looks into it and when it gets fixed. Will leave this issue open until it gets resolved.

**Comment by justdancer55** [comment]
Hi! I didn't know where to leave this but instagram ++ 10.12 crashes when I try to open my direct messages :( please help

**Comment by JMccormick264** [comment]
Thank you for the report. Go ahead abdmake a issue request https://github.com/eni9889/IG-PP-Issues

**Comment by HugaShire** [comment]
You said youll leave it open till it is fixed, why is it closed?

**Comment by JMccormick264** [comment]
My repo isn't a place for issue reports. Leave one on the repo I linked and wait for him to fix it. What is the Issue #? I can tell him.
