### ISSUE TITLE
Rename app to have ++ suffix?

### ISSUE THREAD

**Issue by gqshell** [JMccormick264/PPAppsIPARepo#73]
When I side load the YouTube++ ipa the icon on my ipad just says YouTube.  Is there a way to rename it to have the ++suffix to differentiate from the original YouTube app?  Thanks!

**Comment by JMccormick264** [comment]
Yes. I can do that when I update it again. Do you want the duplicated app to have the ++ suffix? or would you want duplicate + non duplicate to have the ++ suffix too?

**Comment by XyloMyloto** [comment]
I actually like the app not having the ++ suffix, it looks nicer and cleaner and I'm not using the official apps either so that doesn't matter. But I don't want you to do double work though.

**Comment by JMccormick264** [comment]
@XyloMyloto it's not double the work. I just change 2 settings when I make the one with the ++ as a suffix for duplicate.

**Comment by XyloMyloto** [comment]
@JMccormick264 Awesome then! That would be a nice addition to those who want a ++ suffix on their apps. 👍

**Comment by JMccormick264** [comment]
Added :)

**Comment by gqshell** [comment]
Thanks for the quick work.  You're awesome!  I just use the duplicate one... in case I forget to resign I can use the original still.  So having the different app names is helpful for me to tell which is which on the home screen :)
