### ISSUE TITLE
Phantom for snapchat DUBLICATE app?

### ISSUE THREAD

**Issue by Yivensky** [JMccormick264/PPAppsIPARepo#74]
Hi,
It is possible to do the same thing than insta, youtube etc? To do an ipa dublicate to install phantom & app store snapchat to keep notifications ? 
Thanks

**Comment by JMccormick264** [comment]
I am not sure if Notifications work in that way like they used to. Last time I tried, it didn't work. But I can try again.

**Comment by Yivensky** [comment]
I think it can works because when we are disconnect because of an other devices, the notifications still appear even disconnect
Thanks to try :)
But I tried to do an "dublicate" by change de bundle name but I failed

**Comment by JMccormick264** [comment]
I do not think that is possible.
