### ISSUE TITLE
Snapchat video sending is not working

### ISSUE THREAD

**Issue by thatrandompersonn** [JMccormick264/PPAppsIPARepo#79]
i have updated snapchat ++ and everything up to date but the videos are under 10 seconds yet they still will not send.

**Comment by JMccormick264** [comment]
Have you experienced this bug before?

**Comment by thatrandompersonn** [comment]
this has only happened on this update and the last update and it happens every time i try it

**Comment by JMccormick264** [comment]
Should be fixed now. Try again.
