### ISSUE TITLE
Installing 2 apps

### ISSUE THREAD

**Issue by abbieg44** [JMccormick264/PPAppsIPARepo#81]
Not sure why but when I try to install twitter ++ & then snapchat ++ (duplicate app with suffix) with impactor they just replace one another, so twitter ++ will turn into snapchat ++ .

**Comment by HugaShire** [comment]
@JMccormick264 Their bundle ID is the same. Can you change it?

**Comment by JMccormick264** [comment]
Shoud be fixed.
