### ISSUE TITLE
Pandora++

### ISSUE THREAD

**Issue by ElmHoe** [JMccormick264/PPAppsIPARepo#82]
On the latest version of pandora++,
It’ll load up and crash after about 3-5 seconds. Unable to play any songs.

Reproduction Steps:
- Open the app
- Make sure to be logged in
- When loading the main screen, it’ll now crash.

Tested on an iPhone 7 iOS 11 Developer Beta 3

**Comment by berrios30** [comment]
on the ios 10.3.1 everything is working except the change the quality over wifi from normal to high and the download don't work keep getting cant download music due to copyright laws the skipping works and so on just thoese what i found out that dont work though

**Comment by ElmHoe** [comment]
resolved in commit e2bb7018161efc4d2d73a4d7ef3e3e5c61d684bf
