### ISSUE TITLE
Soundcloud++

### ISSUE THREAD

**Issue by silversam2000** [JMccormick264/PPAppsIPARepo#84]
Whenever i install Soundcloud++ is will never let me log in saying a network error  and if i pick a song without logging in it crashes

**Comment by brent1000** [comment]
yeah because go songs are server side, checks md5 hash to see if you'r e ago member, if not it falls back to a value thats modded to force the app to think its a go member which its not, thats what results in the crashes

**Comment by JMccormick264** [comment]
Go and Go+ songs will cause that.
