### ISSUE TITLE
Instagram++ Video controls and auto refresh

### ISSUE THREAD

**Issue by Fizzgiggg** [JMccormick264/PPAppsIPARepo#91]
ios 10.3.3
Instagram++ 10.32
Sideloaded/ no jailbreak.

Video controls don't work.

Stop automatic refresh doesn't work after 1 or 2 minutes of app being in background.

**Comment by JMccormick264** [comment]
Should be fixed now. [Find the latest here](https://github.com/JMccormick264/InstagramPP/releases)
