### ISSUE TITLE
Deezer++, clicks not working

### ISSUE THREAD

**Issue by kimster11** [JMccormick264/PPAppsIPARepo#94]
http://imgur.com/a/zfn5D

In Deezer++, I cannot click on the song and the only way to play a song I want is through shuffle playlist and select in queue list.

Regardless of this issue, I appreciate very much of your effort and contributions to this work.

**Comment by yxnshx** [comment]
i got the exact same issue for like 2 weeks now . i tried restarting device, older version , installing multiple times well doesn't work at all. thank you

**Comment by JMccormick264** [comment]
I do not make the tweak. So I am not sure of a solution.
