### ISSUE TITLE
Facebook++ - Crashes when clicking the notifications

### ISSUE THREAD

**Issue by maverick1925** [JMccormick264/PPAppsIPARepo#96]
Crashes when clicking the notifications

**Comment by JMccormick264** [comment]
Are you using the latest Facebook++?

**Comment by maverick1925** [comment]
Yeah. The v137

**Comment by JMccormick264** [comment]
Yeah. I have been crashing on it a lot. Even pre 137. It doesn't crash for me on JB. Can ask Unlim what he thinks about why it is still crashing on sideload.

**Comment by radiochild577** [comment]
Clicking notifications (in the notifications tab) also results in a crash for me - this is the case on all versions of FB++ above FB version 86. It doesn't happen on every notification though - clicking a notification about a friend mentioning me in a comment does not result in a crash. It's mainly notifications from my groups that result in a crash. 

Strangely enough, clicking my groups from a search result also results in a crash so I have no way to view my groups.

**Comment by JMccormick264** [comment]
yeah. It seems to be a sideloaded issue. It doesn't happen on JB which is odd. You would expect the same to happen on Sideload as it does on JB.
