### ISSUE TITLE
Phantom For Snapchat

### ISSUE THREAD

**Issue by TariqFakhouri** [JMccormick264/PPAppsIPARepo#99]
Please Update Phantom Tool To The Latest Version 2.3 For Snapchat Version 10.17.1.
Thanks.

**Comment by JMccormick264** [comment]
You can't install it with Impactor. It will give you a Network Extension error. I have tried. Snap+ works fine.

**Comment by TariqFakhouri** [comment]
aha thanks for letting me know, I thought the .ipa file I tried was damaged.

**Comment by JMccormick264** [comment]
nope. I tried compiling it myself. Still got the network extension error. I think Cokepokes put it in there intentionally. Otherwise Snap+ would have gotten it too if it was Snapchats doing.

**Comment by TariqFakhouri** [comment]
ya, thanks anyway 👍
